In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])

In [10]:
print(x)
print(type(x))
print(x.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64


In [12]:
x.shape

(4,)

# Two dimensional Array


In [17]:
y = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [18]:
print(y.shape) # Dimension

(3, 4)


In [19]:
print(y.size) # Total elements

12


In [21]:
z = np.array([1,2,3,4], dtype=np.int8)

In [22]:
z

array([1, 2, 3, 4], dtype=int8)

In [24]:
np.save('my_array', y)

In [26]:
y2 = np.load('my_array.npy')


In [28]:
print(y2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
np.empty(2) 


array([-2.00000000e+000,  1.39665569e-314])

# Creating Arrays

In [6]:
# Creating 3x4 array with zeros
x = np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# Similar to create it with 1
x = np.ones((3,4), dtype=np.int16)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [9]:
# Create array with a specified number
x = np.full((3,4), 5)
x

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [15]:
# Create a Identity Matrix (Becauuse i and itenty matdix, this created a square matrix)
x = np.eye(5)
x


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# Create a diag matrix with custom values
x = np.diag([1,2,3,4,5,6])
x

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

# Arange


In [18]:
# Createing an arange array
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [20]:
# Createing an arange array witrh start, stop
x = np.arange(5, 10)
x

array([5, 6, 7, 8, 9])

In [22]:
# THe same but more arguments np.arange(start,stop,step)
x = np.arange(5, 10, 2)
x

array([5, 7, 9])

In [25]:
# Lindaspace  (Create array with equial space)
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0,25,10)
x

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

## Reshape

In [27]:
# It gives a new shape to an array without changing its data. 

# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)
print(x)

# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [28]:
# SImilar but as a method

# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Random

In [29]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
x = np.random.randint(4,15,size=(3,2))
x

array([[ 6,  9],
       [ 8,  5],
       [12, 13]])

In [31]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
x = np.random.random((3,3))
x

array([[0.53597279, 0.49290168, 0.37346694],
       [0.14800269, 0.16546171, 0.27172453],
       [0.22508481, 0.11115856, 0.53063226]])

In [34]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
x = np.random.normal(0, 0.1, size=(1000,1000))

# We print information about X
print(x)
print('X has dimensions:', x.shape)
print('X is an object of type:', type(x))
print('The elements in X are of type:', x.dtype)
print('The elements in X have a mean of:', x.mean())
print('The maximum value in X is:', x.max())
print('The minimum value in X is:', x.min())
print('X has', (x < 0).sum(), 'negative numbers')
print('X has', (x > 0).sum(), 'positive numbers')

[[ 0.14563016  0.00166188 -0.04403397 ...  0.05739434  0.11229283
  -0.05772209]
 [-0.09071558 -0.10882259 -0.18566865 ...  0.03337061 -0.01318337
   0.07527685]
 [-0.2642557  -0.02435627  0.04161641 ... -0.03577698  0.04078593
  -0.14213898]
 ...
 [-0.05189377  0.00866537 -0.13974822 ...  0.1556803  -0.08093479
  -0.07176053]
 [ 0.20820155  0.06761469 -0.17754914 ...  0.01787938  0.11083189
  -0.01368989]
 [ 0.1158486  -0.22036504  0.0566778  ... -0.05383941 -0.00054732
  -0.09846337]]
X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 1.705563375857212e-05
The maximum value in X is: 0.4683745456574007
The minimum value in X is: -0.4723739346867742
X has 500243 negative numbers
X has 499757 positive numbers
